# continuous integration

name: LO_MQTT_NODEJS_CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the prod branch
  push:
    branches:
     - prod
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 20.x ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          frontend/package-lock.json

    - name: Install dependencies
      # npx force-resolutions : in case of Permission denied: run it locally to fix package-lock.json
      run: |
        echo "install"
        npm run preinstall
        npm install
        echo "show outdated (if any)"
        npm outdated --depth=3 || echo "you must think about update your dependencies :)"

    # vulnerabilities cf ./AUDIT.md
    - name: Npm audit
      uses: oke-py/npm-audit-action@v2
      continue-on-error: true # HIGH with no fix
      with:
        audit_level: high
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_assignees: creharmony
        issue_labels: cybersécurité,créée-par-un-robot
        dedupe_issues: true
        production_flag: true

    # possible improvements
    # - tests